from __future__ import annotations

from .registry import register_presets


BUILTIN_PRESET_SCENARIOS: dict[str, dict[str, object]] = {
    "Slow Mobile + Vulnerable DOM": {
        "intent_text": "Validate generated fixes under degraded mobile conditions with DOM exploit exposure.",
        "network_profile_label": "3G Degraded",
        "latency_ms": 520,
        "packet_loss_pct": 8,
        "cpu_budget_label": "1 vCPU",
        "memory_budget_label": "512 MB",
        "db_engine_label": "Postgres 15",
        "chaos_mode": False,
        "vulnerable_dom": True,
        "sql_injection": False,
        "auth_bypass": False,
        "third_party_outage": False,
        "strict_rate_limit": True,
        "injection_language": "python",
        "target_path": "/workspace/injected/main.py",
        "run_command": "python /workspace/injected/main.py",
        "payload_text": "print('simulate degraded mobile edge case')",
        "spin_now": False,
    },
    "Auth Chaos Drill": {
        "intent_text": "Stress test generated patches for token expiry races, bypass behavior, and partial upstream failures.",
        "network_profile_label": "Edge Failure",
        "latency_ms": 390,
        "packet_loss_pct": 5,
        "cpu_budget_label": "2 vCPU",
        "memory_budget_label": "1 GB",
        "db_engine_label": "MySQL 8",
        "chaos_mode": True,
        "vulnerable_dom": False,
        "sql_injection": False,
        "auth_bypass": True,
        "third_party_outage": True,
        "strict_rate_limit": True,
        "injection_language": "node",
        "target_path": "/workspace/injected/main.js",
        "run_command": "node /workspace/injected/main.js",
        "payload_text": "console.log('auth chaos drill active');",
        "spin_now": False,
    },
    "SQL Storm + Tight Limits": {
        "intent_text": "Benchmark generated sanitization logic under SQL attack pressure and strict rate limiting.",
        "network_profile_label": "WiFi Office",
        "latency_ms": 140,
        "packet_loss_pct": 1,
        "cpu_budget_label": "4 vCPU",
        "memory_budget_label": "2 GB",
        "db_engine_label": "Postgres 15",
        "chaos_mode": True,
        "vulnerable_dom": False,
        "sql_injection": True,
        "auth_bypass": False,
        "third_party_outage": False,
        "strict_rate_limit": True,
        "injection_language": "shell",
        "target_path": "/workspace/injected/main.sh",
        "run_command": "sh /workspace/injected/main.sh",
        "payload_text": "echo 'running sql storm drill'",
        "spin_now": False,
    },
    "Third-Party Timeout Cascade": {
        "intent_text": "Test generated patches when upstream dependencies are unstable and requests timeout intermittently.",
        "network_profile_label": "3G Degraded",
        "latency_ms": 460,
        "packet_loss_pct": 6,
        "cpu_budget_label": "2 vCPU",
        "memory_budget_label": "1 GB",
        "db_engine_label": "Postgres 15",
        "chaos_mode": True,
        "vulnerable_dom": False,
        "sql_injection": False,
        "auth_bypass": False,
        "third_party_outage": True,
        "strict_rate_limit": True,
        "injection_language": "python",
        "target_path": "/workspace/injected/main.py",
        "run_command": "python /workspace/injected/main.py",
        "payload_text": "print('simulate upstream timeout cascade')",
        "spin_now": False,
    },
    "CPU Spike Recovery": {
        "intent_text": "Evaluate whether generated retries and backoff logic survive CPU starvation windows.",
        "network_profile_label": "WiFi Office",
        "latency_ms": 170,
        "packet_loss_pct": 2,
        "cpu_budget_label": "1 vCPU",
        "memory_budget_label": "1 GB",
        "db_engine_label": "MySQL 8",
        "chaos_mode": True,
        "vulnerable_dom": False,
        "sql_injection": False,
        "auth_bypass": False,
        "third_party_outage": True,
        "strict_rate_limit": False,
        "injection_language": "node",
        "target_path": "/workspace/injected/main.js",
        "run_command": "node /workspace/injected/main.js",
        "payload_text": "console.log('cpu spike resilience check');",
        "spin_now": False,
    },
    "Memory Pressure Leak Hunt": {
        "intent_text": "Probe generated code under low-memory constraints to surface hidden leak behavior and crashes.",
        "network_profile_label": "WiFi Office",
        "latency_ms": 120,
        "packet_loss_pct": 1,
        "cpu_budget_label": "2 vCPU",
        "memory_budget_label": "512 MB",
        "db_engine_label": "MongoDB 7",
        "chaos_mode": True,
        "vulnerable_dom": False,
        "sql_injection": False,
        "auth_bypass": False,
        "third_party_outage": False,
        "strict_rate_limit": True,
        "injection_language": "python",
        "target_path": "/workspace/injected/main.py",
        "run_command": "python /workspace/injected/main.py",
        "payload_text": "print('memory pressure leak hunt active')",
        "spin_now": False,
    },
    "Packet Loss Retry Trap": {
        "intent_text": "Validate idempotency and retry logic when packet loss causes duplicate and partial requests.",
        "network_profile_label": "Edge Failure",
        "latency_ms": 410,
        "packet_loss_pct": 18,
        "cpu_budget_label": "2 vCPU",
        "memory_budget_label": "1 GB",
        "db_engine_label": "Postgres 15",
        "chaos_mode": True,
        "vulnerable_dom": False,
        "sql_injection": False,
        "auth_bypass": True,
        "third_party_outage": True,
        "strict_rate_limit": True,
        "injection_language": "python",
        "target_path": "/workspace/injected/main.py",
        "run_command": "python /workspace/injected/main.py",
        "payload_text": "print('packet loss retry trap')",
        "spin_now": False,
    },
    "Offline-First Failover": {
        "intent_text": "Check whether generated code gracefully degrades when the network is mostly unavailable.",
        "network_profile_label": "Edge Failure",
        "latency_ms": 700,
        "packet_loss_pct": 25,
        "cpu_budget_label": "1 vCPU",
        "memory_budget_label": "1 GB",
        "db_engine_label": "SQLite (No DB Container)",
        "chaos_mode": True,
        "vulnerable_dom": False,
        "sql_injection": False,
        "auth_bypass": False,
        "third_party_outage": True,
        "strict_rate_limit": False,
        "injection_language": "shell",
        "target_path": "/workspace/injected/main.sh",
        "run_command": "sh /workspace/injected/main.sh",
        "payload_text": "echo 'offline-first failover check'",
        "spin_now": False,
    },
    "No-DB Fallback Path": {
        "intent_text": "Verify generated fallback logic when no external database container is available.",
        "network_profile_label": "5G Stable",
        "latency_ms": 50,
        "packet_loss_pct": 0,
        "cpu_budget_label": "2 vCPU",
        "memory_budget_label": "2 GB",
        "db_engine_label": "SQLite (No DB Container)",
        "chaos_mode": False,
        "vulnerable_dom": False,
        "sql_injection": False,
        "auth_bypass": False,
        "third_party_outage": False,
        "strict_rate_limit": False,
        "injection_language": "python",
        "target_path": "/workspace/injected/main.py",
        "run_command": "python /workspace/injected/main.py",
        "payload_text": "print('no-db fallback path check')",
        "spin_now": False,
    },
    "Full Chaos Fire Drill": {
        "intent_text": "Push generated code through an intentionally hostile stack: auth bypass, SQL risk, outages, and high loss.",
        "network_profile_label": "Edge Failure",
        "latency_ms": 780,
        "packet_loss_pct": 22,
        "cpu_budget_label": "1 vCPU",
        "memory_budget_label": "512 MB",
        "db_engine_label": "MySQL 8",
        "chaos_mode": True,
        "vulnerable_dom": True,
        "sql_injection": True,
        "auth_bypass": True,
        "third_party_outage": True,
        "strict_rate_limit": True,
        "injection_language": "shell",
        "target_path": "/workspace/injected/main.sh",
        "run_command": "sh /workspace/injected/main.sh",
        "payload_text": "echo 'full chaos fire drill active'",
        "spin_now": False,
    },
}


def register_builtin_scenarios() -> None:
    register_presets(BUILTIN_PRESET_SCENARIOS)
